# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'freeenzTXOV.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
import os
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QStatusBar,
    QWidget)
if __name__ == "__main__":
    # 環境変数にPySide6を登録
    dirname = os.path.dirname(PySide6.__file__)
    plugin_path = os.path.join(dirname, 'plugins', 'platforms')
    os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = plugin_path
    
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(623, 451)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(340, 340, 111, 51))
        font = QFont()
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(490, 340, 111, 51))
        self.pushButton_2.setFont(font)
        self.dateEdit = QDateEdit(self.centralwidget)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(390, 10, 181, 41))
        font1 = QFont()
        font1.setPointSize(14)
        self.dateEdit.setFont(font1)
        self.dateEdit.setDateTime(QDateTime(QDate(2021, 12, 30), QTime(0, 0, 0)))
        self.free1 = QLineEdit(self.centralwidget)
        self.free1.setObjectName(u"free1")
        self.free1.setGeometry(QRect(140, 80, 113, 22))
        self.free1.setFont(font1)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 80, 71, 21))
        self.label.setFont(font1)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 120, 71, 21))
        self.label_2.setFont(font1)
        self.free5 = QLineEdit(self.centralwidget)
        self.free5.setObjectName(u"free5")
        self.free5.setGeometry(QRect(140, 120, 113, 22))
        self.free5.setFont(font1)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 200, 81, 21))
        self.label_3.setFont(font1)
        self.free15 = QLineEdit(self.centralwidget)
        self.free15.setObjectName(u"free15")
        self.free15.setGeometry(QRect(140, 200, 113, 22))
        self.free15.setFont(font1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 160, 91, 21))
        self.label_4.setFont(font1)
        self.free10 = QLineEdit(self.centralwidget)
        self.free10.setObjectName(u"free10")
        self.free10.setGeometry(QRect(140, 160, 113, 22))
        self.free10.setFont(font1)
        self.free60 = QLineEdit(self.centralwidget)
        self.free60.setObjectName(u"free60")
        self.free60.setGeometry(QRect(140, 280, 113, 22))
        self.free60.setFont(font1)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 240, 91, 21))
        self.label_7.setFont(font1)
        self.free30 = QLineEdit(self.centralwidget)
        self.free30.setObjectName(u"free30")
        self.free30.setGeometry(QRect(140, 240, 113, 22))
        self.free30.setFont(font1)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 280, 81, 21))
        self.label_8.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(360, 120, 101, 21))
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(350, 200, 101, 21))
        self.label_6.setFont(font1)
        self.free8h = QLineEdit(self.centralwidget)
        self.free8h.setObjectName(u"free8h")
        self.free8h.setGeometry(QRect(470, 120, 113, 22))
        self.free8h.setFont(font1)
        self.free15h = QLineEdit(self.centralwidget)
        self.free15h.setObjectName(u"free15h")
        self.free15h.setGeometry(QRect(470, 160, 113, 22))
        self.free15h.setFont(font1)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(380, 240, 91, 21))
        self.label_10.setFont(font1)
        self.free24h = QLineEdit(self.centralwidget)
        self.free24h.setObjectName(u"free24h")
        self.free24h.setGeometry(QRect(470, 200, 113, 22))
        self.free24h.setFont(font1)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(360, 80, 101, 21))
        self.label_11.setFont(font1)
        self.free3d = QLineEdit(self.centralwidget)
        self.free3d.setObjectName(u"free3d")
        self.free3d.setGeometry(QRect(470, 240, 113, 22))
        self.free3d.setFont(font1)
        self.free3h = QLineEdit(self.centralwidget)
        self.free3h.setObjectName(u"free3h")
        self.free3h.setGeometry(QRect(470, 80, 113, 22))
        self.free3h.setFont(font1)
        self.free3h.setLayoutDirection(Qt.LeftToRight)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(350, 160, 111, 21))
        self.label_12.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.free1, self.free5)
        QWidget.setTabOrder(self.free5, self.free10)
        QWidget.setTabOrder(self.free10, self.free15)
        QWidget.setTabOrder(self.free15, self.free30)
        QWidget.setTabOrder(self.free30, self.free60)
        QWidget.setTabOrder(self.free60, self.free3h)
        QWidget.setTabOrder(self.free3h, self.free8h)
        QWidget.setTabOrder(self.free8h, self.free15h)
        QWidget.setTabOrder(self.free15h, self.free24h)
        QWidget.setTabOrder(self.free24h, self.free3d)
        QWidget.setTabOrder(self.free3d, self.dateEdit)
        QWidget.setTabOrder(self.dateEdit, self.pushButton_2)
        QWidget.setTabOrder(self.pushButton_2, self.pushButton)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u9589\u3058\u308b", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u9001\u4fe1", None))
        self.dateEdit.setDisplayFormat(QCoreApplication.translate("MainWindow", u"yyyy\u5e74MM\u6708dd\u65e5", None))
        self.free1.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"1\u5206\u52a0\u901f", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"5\u5206\u52a0\u901f", None))
        self.free5.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"15\u5206\u52a0\u901f", None))
        self.free15.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"10\u5206\u52a0\u901f", None))
        self.free10.setText("")
        self.free60.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"30\u5206\u52a0\u901f", None))
        self.free30.setText("")
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"60\u5206\u52a0\u901f", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"8\u6642\u9593\u52a0\u901f", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"24\u6642\u9593\u52a0\u901f", None))
        self.free8h.setText("")
        self.free15h.setText("")
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"3\u65e5\u52a0\u901f", None))
        self.free24h.setText("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"3\u6642\u9593\u52a0\u901f", None))
        self.free3d.setText("")
        self.free3h.setText("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"15\u6642\u9593\u52a0\u901f", None))
    # retranslateUi

